name: API Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest

    env:
      SEAHOT_TOKEN: ${{ secrets.SEAHOT_TOKEN }}
      TEST_ACCOUNT_ID: ${{ secrets.TEST_ACCOUNT_ID }}
      TEST_CHARACTER_ID: ${{ secrets.TEST_CHARACTER_ID }}
      TEST_FCM_TOKEN: ${{ secrets.TEST_FCM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API tests
        run: pytest -q

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: reports/allure-html/latest
